services:
  agent:
    image: ${PROJECT_NAME}
    build: .
    command: sleep infinity
    volumes:
      - ../:/workspace
      - $HOME/.config/gcloud:/root/.config/gcloud
    environment:
      - GOOGLE_GENAI_USE_VERTEXAI=${GOOGLE_GENAI_USE_VERTEXAI}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - GOOGLE_CLOUD_LOCATION=${GOOGLE_CLOUD_LOCATION}
      - GOOGLE_CLOUD_SA_EMAIL=${GOOGLE_CLOUD_SA_EMAIL}
      - GENMEDIA_BUCKET=${GENMEDIA_BUCKET}
      - REFERENCE_IMAGE_URI=${REFERENCE_IMAGE_URI}
      - IMAGEN_INSTRUCTION=${IMAGEN_INSTRUCTION}
      # - MCP_VEO_ENDPOINT=${MCP_VEO_ENDPOINT}
      # - MCP_IMAGEN_ENDPOINT=${MCP_IMAGEN_ENDPOINT}

  # mcp-veo:
  #   image: ${PROJECT_NAME}-mcp-genmedia
  #   build: ./.mcp-genmedia/
  #   command: /mcp-veo-go -transport sse
  #   volumes:
  #     - $HOME/.config/gcloud/application_default_credentials.json:/gcloud/creds.json
  #   environment:
  #     - GOOGLE_APPLICATION_CREDENTIALS=/gcloud/creds.json
  #     - PROJECT_ID=${GOOGLE_CLOUD_PROJECT}
  #     - LOCATION=${GOOGLE_CLOUD_LOCATION}
  #     - GENMEDIA_BUCKET=${GENMEDIA_BUCKET}
  #   container_name: mcp-veo

  # mcp-imagen:
  #   image: ${PROJECT_NAME}-mcp-genmedia
  #   build: ./.mcp-genmedia/
  #   command: /mcp-imagen-go -transport sse
  #   volumes:
  #     - $HOME/.config/gcloud/application_default_credentials.json:/gcloud/creds.json
  #   environment:
  #     - GOOGLE_APPLICATION_CREDENTIALS=/gcloud/creds.json
  #     - PROJECT_ID=${GOOGLE_CLOUD_PROJECT}
  #     - LOCATION=${GOOGLE_CLOUD_LOCATION}
  #     - GENMEDIA_BUCKET=${GENMEDIA_BUCKET}
  #   container_name: mcp-imagen
